name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project 
        uses: actions/checkout@v2

      - name: setup node version 
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: resolve dependencies 
        run: npm CI

      - name: running tests
        run: npm test -- --coverage
        env:
          CI: true 

    