name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project 
        uses: actions/checkout@v2

      - name: setup node version 
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: resolve dependencies 
        run: npm ci

      - name: running tests
        run: npm test -- --coverage
        env:
          CI: true 

      - name: build project
        if: github.event_name == 'push'
        run: npm run buil

      - name: deploy to staging 
        if: github.event_name == 'push'   
        run: npx surge --project ./build --domain ci20202-samuel-tavaress10.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}  